functionsDirectory = "C:\\Users\\André Araújo\\Documents\\GitHub\\meuPortfolio\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\André Araújo\\Documents\\GitHub\\meuPortfolio\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\André Araújo\\Documents\\GitHub\\meuPortfolio\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]